-- ============================================
-- Migration 002 — REMOVED / CONSOLIDATED
-- All tables are now in 001_initial_schema.sql
-- This file is intentionally empty.
-- ============================================
-- Previous version had errors:
--   - Referenced non-existent 'agreements' table
--   - Used auth.uid() instead of requesting_user_id()
--   - Duplicated products table as content_inventory
--   - Duplicated feedback_reviews as feedback_requests
--   - scheduled_emails had incompatible column schema
-- All fixed and consolidated into 001.
