-- ============================================
-- Migration 003 — REMOVED / CONSOLIDATED
-- Ticket replies RLS fix is now in 001_initial_schema.sql
-- This file is intentionally empty.
-- ============================================
